language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python covid-19-uk-scraper
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: master
